pipeline:
  identifier: Build_unkeyed_unkey_1716300454858
  name: Build unkey
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1716300426832
        repoName: unkeyed/unkey
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    shell: Sh
                    command: |-
                      cd apps/vault
                      docker build .
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    command: npm run build
                  timeout: ""
                  type: Run
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
        type: CI
